### ISSUE TITLE
Reservations before registrations

### ISSUE THREAD

**Issue by BrendaH** [evolution-events/Artaxerxes#16]
Registration starts with a reservation for a set amount of time so users can fill in all forms without too much stress to 'at least be in'.

**Comment by matthijskooijman** [comment]
One alternative would be to work with a lottery system, which would completely remove the time pressure from the registration process, removing the need for such a two-step process.

**Comment by matthijskooijman** [comment]
The register/confirm flow is in the process of being implemented and the lottery alternative is part of #36 so I'm closing this issue.
