### ISSUE TITLE
iDeal payment

### ISSUE THREAD

**Issue by ReneB** [evolution-events/Artaxerxes#21]
it would be very, very cool to implement iDeal payment, which would definitely support just registering, paying and be done with it. It should probably be optional, but it might be the default.

**Comment by BrendaH** [comment]
Mollie provides a Python API: https://github.com/mollie/mollie-api-python
Specifically for Django there's this package, but this seems to be deprecated without linking to a newer project: https://github.com/peeb/django-mollie-ideal
Deze lijkt nog wel onderhouden maar gaat er van uit dat je een e-commerce systeem gebruikt: https://github.com/JorrandeWit/django-oscar-mollie
