### ISSUE TITLE
"This is my first event" tickbox on the registration form

### ISSUE THREAD

**Issue by ReneB** [evolution-events/Artaxerxes#28]
Some discussion in the Dutch Larp Platform leads me to believe that at the very least, it can be useful for an organizer to know who of the participants are playing for the first time. This tickbox would help the organizers approach these participants and help them out with any questions or problems.

**Comment by matthijskooijman** [comment]
I wonder if this is something to implement globally, or it would be sufficient to add this as an event-specific option (which would work, and is flexible, but maybe not fully elegant).

**Comment by matthijskooijman** [comment]
Reconsidering this, I think this should be an event-specific field, since it is only relevant if the event will actually have a way to deal with it. So I'm closing this as wontfix.
