### ISSUE TITLE
Invite-only events

### ISSUE THREAD

**Issue by ReneB** [evolution-events/Artaxerxes#41]
It should be possible to open the registrations to only a select group of people. Two implementations might be a "secret link" and requiring invited users to have a profile and select them when opening registrations.

**Comment by matthijskooijman** [comment]
Implemented in c1275fbc34092aac884680d5caf2063f9a1bfbaa. It is now implemented using a Group that we can fill with invited users. If we want a secret link approach as well (to e.g. simplify the process and/or include people who do not have an account yet), I would suggest we create an invite link that will add anyone who clicks it to the invite group, so we can reuse the invite group logic after the initial link click.
