### ISSUE TITLE
Ask for firstname/lastname on account creation

### ISSUE THREAD

**Issue by matthijskooijman** [evolution-events/Artaxerxes#46]
Currently, the firstname/lastname is left empty when a local account is registered. For social accounts, this information is filled in (when available).

For a local account this info should probably be asked on registration. This might require a custom signup form (there does not seem to be a config for "additional signup fields" at least).

Should we make first_name and last_name required fields on User?

**Comment by ReneB** [comment]
Yes.

**Comment by ReneB** [comment]
How could we go about doing this? Can we add it to the registration flow, so the first page of "prepare registration" would ask you about your first and last name?

**Comment by matthijskooijman** [comment]
That would probably be the easiest, along with the rest of the personal details.

**Comment by matthijskooijman** [comment]
It would make sense to eventually ask this on account creation, but even then it would make sense to at least show, and probably allow changing, the name during event registration as well.

**Comment by matthijskooijman** [comment]
I've created #81 for asking the name during event (pre)registration, this issue is now only about asking during account creation. Only #81 is needed for the MVP, but while implementating something else, it was easy to immediately also implement this.
