### ISSUE TITLE
Allow users to opt-in to mailings on account creation

### ISSUE THREAD

**Issue by matthijskooijman** [evolution-events/Artaxerxes#50]
In the existing system, we just remove a user's e-mail address when they want to opt-out. With Artaxerxes, the e-mailaddress is mandatory and used for login, so this would effectively disable an account. Adding an explicit opt-in checkbox would be better anyway, and solve this problem.

**Comment by BrendaH** [comment]
Where would we put it? It's not exactly address or medical details. Perhaps under something new like 'privacy settings' where we could also put the 'do not show my full name on lists' option. And perhaps (but that is a different issue) the "when to throw medical details away", if that is still a thing.

**Comment by matthijskooijman** [comment]
Sounds like a useful grouping, yes. In terms of models, that probably just means to add fields on ArtaUser? Or would this be part of a separate model (or profile)?

**Comment by ReneB** [comment]
I could imagine "mailinglists" as a separate model, which would allow opting into or out of several different groups - "General", "On the Styx", et cetera. That would just be a whole bunch of links to users or their profiles, I'm guessing.

**Comment by matthijskooijman** [comment]
For the MVP, we will add two checkboxes to a user (or maybe in another model, but in ArtaUser would be fine for now):
 - Keep me updated about Dutch events & activities
 - Keep me updated about international events & activities

For the MVP, we should then offer these checkboxes when a user creates an account. Later, we must also allow editing them later, which is #89.

Also, these checkboxes should log consent, see #72.

**Comment by matthijskooijman** [comment]
I also looked a bit at third-party apps for consent tracking, but I did not find anything directly useful. https://github.com/raratiru/django-letsagree comes close, but is centered about consent for *using* the site. It allows different usergroups with different terms, and also allows versioning terms.

https://django-cookie-consent.readthedocs.io/en/latest/ is centered about managing (and automatically applying) cookie preferences.

**Comment by matthijskooijman** [comment]
To offer these checkboxes, we probably need a customized signup form, using the `ACCOUNT_SIGNUP_FORM_CLASS` setting (see https://django-allauth.readthedocs.io/en/latest/configuration.html).

**Comment by matthijskooijman** [comment]
I ended up implementing just a single "keep me updated about new events" checkbox, rather than two, since I was not entirely sure whether Dutch/International was the perfect distinction here (and whether it would cover all cases together). Also, because it is a lot easier to split or limit consent than merging or broadening consent, starting out with just a single checkbox seemed better for now.
