### ISSUE TITLE
Revise explanations offered by the system

### ISSUE THREAD

**Issue by matthijskooijman** [evolution-events/Artaxerxes#64]
After the first moving bits are in place, we should do a pass over the system and add additional help texts and explanations. In particular, I'm thinking of things like:
 - [x] How does login/user management work (and encourage people to reuse their existing accounts).
 - [x] When and how are user data remembered and when are they deleted?
 - [x] Note that user data is shared between active registrations
 - [x] How the registration flow (first prepare, then register) works -> page exists but may need revising
 - [x] How information is used (partly in the system, partly as a reference to a privacy statement, see #85.
 - [x] Encourage people to limit allergies to actual allergies ("Please do not tell us which kinds of food you don’t like here - tell us which kinds of food condemn you to an interesting night of gastric pandemonium." ?)
 - [x] Revise the registration confirmation page and email.
 - [x] Dashboard now shows "Registration open" heading even when registration is not open but only preregistration is. Should probably be renamed toe something else?
 - [x] Indicate that some information (personal details, medical details, emergency contacts) is shared between multiple registrations (might not be relevant until we have multiple events, though).

 - [x] From https://github.com/evolution-events/Artaxerxes/issues/42#issuecomment-583744687: (handled in the privacy policy)
> We should add this information, like "this information will be read by our emergency team and, when required, be shared with any medical personnel" to the form. This is all we need to do before first registrations.

**Comment by BrendaH** [comment]
Do we want to have this hardcoded in the templates, or do we want to have this as content which is editable in the admin? (Something to take into account is the possibility to translate stuff... )

**Comment by matthijskooijman** [comment]
For the MVP, hardcoding is probably sufficient. In the end, it might still be good enough, since this usually describes how the system works, though some of it might describe the policies of EE that are not inherent to the system itself. But even then, we can make things configurable when we find we really need that, I guess.

**Comment by ReneB** [comment]
I can't say for sure how it is in the Django world, but in the Rails world, quite a lot of 'i18n' solutions allow for local (database-based) overrides through some kind of web interface or backend data loading, to allow changing the translation values. In that way, you could put the default translation into a config file and override it through the database with the EE-specific policy info.

**Comment by matthijskooijman** [comment]
> quite a lot of 'i18n' solutions allow for local (database-based) overrides through some kind of web interface or backend data loading, to allow changing the translation values. 

I think Django has no such support builtin, but I can imagine there's plenty of third-party middlewares that implement exactly that, which might indeed offer sufficient customization.

**Comment by ReneB** [comment]
> I think Django has no such support builtin

Neither does Rails, I think - I was indeed referring to third-party gems or libraries.

**Comment by ReneB** [comment]
I think it would be smart to, as assistance, render `required` form fields a bit different from other form fields. We can target those specifically as in this [CodePen](https://codepen.io/chriscoyier/pen/ouvFq).

I don't know _how_ they should look, though.

**Comment by ReneB** [comment]
I feel that some bits of these might be part of a sort of "manual" or something? For example, a bit more information about how "preparation" and "registration" differ might help. It's a bit hard to explain in a few short lines.

**Comment by matthijskooijman** [comment]
I improved one more sentence, with that I think this is done.
