### ISSUE TITLE
Allow editing name, personal details, medical details and emergency contacts

### ISSUE THREAD

**Issue by matthijskooijman** [evolution-events/Artaxerxes#79]
Currently, these can only be specified during registration. After MVP, we should allow these to be changed before/after registration.

**Comment by BrendaH** [comment]
I think that 'emergency contacts' should also be on this page. (app people: index.html and according views of course)

**Comment by BrendaH** [comment]
Something to think about: the medical info and emergency contacts can only be stored when someone is also registered (or preparing registration) for an event. So if someone is between events, this data should not be filled in, right? (personal details like address can be kept and updated)

**Comment by matthijskooijman** [comment]
Indeed, if there is no current registration, I do not think that there should be a way to add/edit medical details (since there would not be a good moment to delete them again, or they might be deleted immediately again, depending on how we implement the deletion).

**Comment by matthijskooijman** [comment]
If someone edits the Medical detais "event_risks" field, there should probably also be a notification e-mail, just in case they add something that is relevant for the organizers well-before the event (i.e. when it is not sufficient for the safety coordinator to review the info in the week before the event).

**Comment by matthijskooijman** [comment]
Once we implement this, we should update this message: ff823a63aab7565dc1e879dd59c46ac6dd99fb5d

**Comment by matthijskooijman** [comment]
This is now implemented by the commits above. It is possible to edit this data by editing an active registration. There is no direct interface for editing e.g. address data, which is probably fine.
