### ISSUE TITLE
Write privacy statement

### ISSUE THREAD

**Issue by matthijskooijman** [evolution-events/Artaxerxes#85]
We should have a statement about how and why we process data, GDPR-style.

Some things to include (non-exhaustive):
 - First *and* last name will be shared with other users of the system. Objections to this can be e-mailed to us.
 - ...

Some of these things should probably also be shown in the interface (e.g. when entering your name, show how it would be used). This is #64.

**Comment by ReneB** [comment]
Link from #43 : https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-be-informed/ - about what to communicate about the usage of data.

- Discuss how medical data will be used
- Discuss how we will use mail addresses for "marketing" purposes and opt-in/opt-out.

**Comment by ReneB** [comment]
Current version can be found here: https://docs.google.com/document/d/1_1i3RPqRG7TOinCV0JoUE_H3rYw-UnYn2tXY8_5fEWU/edit#

We would, of course, still need to publish this somewhere before we can link to it properly.

**Comment by ReneB** [comment]
I think we can close this one after the two comments in that document have been resolved.

**Comment by matthijskooijman** [comment]
Did we decide where to put it and how to link to it? Maybe just on the website, and link it from the registration confirmation interface and from the login/create account page? And/or in the footer of Arta?

**Comment by ReneB** [comment]
I can tell you where to "put it" ;-)

In the current version of Arta there is a link - I assume it was done by @BrendaH - to the main website, under "Conditions" when confirming your registration. The link is to https://www.evolution-events.nl/algemeen/?pg=privacy . That page does not yet exist, so I'm guessing it was supposed to go there.

I think it would be a proper place, but I'm doubtful whether it should just be website _content_ or a PDF.

**Comment by matthijskooijman** [comment]
We have this policy in place for a while now, so I'm closing this.
